name: Test
on:
  workflow_dispatch:        # 允许手动触发

jobs:
  # ── arm64-v8a Release ────────────────────────────────────────────
  build-arm64:
    name: 123
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all APK artifacts
        run: |
          mkdir -p file
          wget "https://opensource.vivo.com/oss/uploader/download?token=eyJhbGciOiJIUzUxMiJ9.eyJeeXEwTkxpTllTeXlYTFZYREVUVDYwcDJaJUNaS3d3ViI6ImdmOHIybiIsInN1YiI6IjUxNzQ5MDYwMjIyMTI0MDMyMyIsImV4cCI6MTc4NTM0ODUzMCwiaWF0IjoxNzg1MzQ3OTMwfQ.YRfXot72ms3LwwOqoLu1eEyR7f63SoxbQ1DL6Tk13XHW-lMiAYr9dp4C7hcL3BfH-LmDplze9oKsh5gDZ6LCGQ&appNamevos" -O file/code.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          name: test
          prerelease: true
          files: file/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
