name: Test
on:
  workflow_dispatch:        # 允许手动触发

jobs:
  # ── arm64-v8a Release ────────────────────────────────────────────
  build-arm64:
    name: 123
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all APK artifacts
        run: |
          mkdir -p file
          wget "https://download.lenovo.com/consumer/mobiles/tab_m10_fhd_plus_opensource_tb-x606m_s000213_200302_bmain.tgz" -O file/m10-code.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          name: test
          prerelease: true
          files: file/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
